### ISSUE TITLE
The answer of C6 seems to be wrong 

### ISSUE THREAD

**Issue by yslin9901** [karljackab/DBMS20_hw1_sol#1]
Hello TAs,

It looks like the answer of C6 given by TA yao is not right, I'm not sure if that is my problem, could you help me check the code again?
Thank you very much.

<img width="854" alt="c6.sql" src="https://user-images.githubusercontent.com/50357984/83477842-d7d8a200-a4c6-11ea-9ddb-4b46430062cc.png">

**Comment by yao0510** [comment]
Hi, 
Since `ANY_VALUE`  is any value, this means it won't guarantee same rows or different rows. Actually, `ANY_VALUE` isn't the formal method to solve `ONLY_FULL_GROUP_BY` problem.
In my case, it will be correct always, but we heard that some students have different answers.
I will suggest as mentioned in Teams channel that you can use TA karl's answer to compare and analyze.

![Image 1](https://user-images.githubusercontent.com/37433002/83481355-1e7eca00-a4d0-11ea-810f-76bf27ad2397.jpg)
.

**Comment by yslin9901** [comment]
I see, sorry that I forgot to check the announcement in Teams.
Thank you.
